export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const RECEIVE_CATEGORY_LINKS = 'RECEIVE_CATEGORY_LINKS';
export const RECEIVE_LINKS = 'RECEIVE_LINKS';
export const SHOW_LINK = 'SHOW_LINK';
